version: '3'

services: 
  #Database
  db:
    image: mysql:5.7
    #volumes maps the specified folder(starting point of the folder addres is where the docker-compose.yml is located) onto a location inside the docker container. everything before the ':' refers to the locations of your PC and everything after the ':' refers to the location in the container. Maping means that everything that happens in the PC directory will be reflected in the container directory. 
    ##########
    volumes: 
      - db_data:/var/lib/mysql

    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  #phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports: 
      - '8080:80'
    environment: 
      PMA_HOST: db 
      MYSQL_ROOT_PASSWORD: password
    networks:
     - wpsite
  #Wordpress
  wordpress: 
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    ########
    volumes: ['./:/var/www/html']

    environment: 
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks: 
      - wpsite
networks:
  wpsite:

volumes:
  db_data: